// Banks
export const CREATE_ACCESS = 'CREATE_ACCESS';
export const CREATE_ALERT = 'CREATE_ALERT';
export const CREATE_OPERATION = 'CREATE_OPERATION';
export const DELETE_ACCESS = 'DELETE_ACCESS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const DELETE_ALERT = 'DELETE_ALERT';
export const DELETE_OPERATION = 'DELETE_OPERATION';
export const MERGE_OPERATIONS = 'MERGE_OPERATIONS';
export const RUN_ACCOUNTS_SYNC = 'RUN_ACCOUNTS_SYNC';
export const RUN_BALANCE_RESYNC = 'RUN_BALANCE_RESYNC';
export const RUN_OPERATIONS_SYNC = 'RUN_OPERATIONS_SYNC';
export const SET_OPERATION_CUSTOM_LABEL = 'SET_OPERATION_CUSTOM_LABEL';
export const SET_OPERATION_CATEGORY = 'SET_OPERATION_CATEGORY';
export const SET_OPERATION_TYPE = 'SET_OPERATION_TYPE';
export const SET_OPERATION_BUDGET_DATE = 'SET_OPERATION_BUDGET_DATE';
export const UPDATE_ALERT = 'UPDATE_ALERT';

// UI
export const SET_IS_SMALL_SCREEN = 'SET_IS_SMALL_SCREEN';
export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';
export const SET_SEARCH_FIELDS = 'SET_SEARCH_FIELDS';
export const RESET_SEARCH = 'RESET_SEARCH';
export const TOGGLE_SEARCH_DETAILS = 'TOGGLE_SEARCH_DETAILS';
export const LOAD_THEME = 'LOAD_THEME';
export const UPDATE_MODAL = 'UPDATE_MODAL';
export const TOGGLE_MENU = 'TOGGLE_MENU';

// Categories
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

// Budgets
export const SET_BUDGETS_PERIOD = 'SET_BUDGETS_PERIOD';
export const FETCH_BUDGETS = 'FETCH_BUDGETS';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const RESET_BUDGETS = 'RESET_BUDGETS';

// Settings
export const EXPORT_INSTANCE = 'EXPORT_INSTANCE';
export const IMPORT_INSTANCE = 'IMPORT_INSTANCE';
export const SEND_TEST_EMAIL = 'SEND_TEST_EMAIL';
export const SET_DEFAULT_ACCOUNT = 'SET_DEFAULT_ACCOUNT';
export const SET_SETTING = 'SET_SETTING';
export const UPDATE_ACCESS = 'UPDATE_ACCESS';
export const UPDATE_ACCESS_AND_FETCH = 'UPDATE_ACCESS_AND_FETCH';
export const UPDATE_WEBOOB = 'UPDATE_WEBOOB';
export const GET_WEBOOB_VERSION = 'GET_WEBOOB_VERSION';
export const GET_LOGS = 'GET_LOGS';
export const CLEAR_LOGS = 'CLEAR_LOGS';

// Demo
export const ENABLE_DEMO_MODE = 'ENABLE_DEMO_MODE';
export const DISABLE_DEMO_MODE = 'DISABLE_DEMO_MODE';
