// Banks
export const CREATE_ACCESS = 'CREATE_ACCESS';
export const CREATE_ALERT = 'CREATE_ALERT';
export const CREATE_OPERATION = 'CREATE_OPERATION';
export const DELETE_ACCESS = 'DELETE_ACCESS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ALERT = 'DELETE_ALERT';
export const DELETE_OPERATION = 'DELETE_OPERATION';
export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS';
export const LOAD_OPERATIONS = 'LOAD_OPERATIONS';
export const MERGE_OPERATIONS = 'MERGE_OPERATIONS';
export const RUN_ACCOUNTS_SYNC = 'RUN_ACCOUNTS_SYNC';
export const RUN_BALANCE_RESYNC = 'RUN_BALANCE_RESYNC';
export const RUN_SYNC = 'RUN_SYNC';
export const SET_OPERATION_CUSTOM_LABEL = 'SET_OPERATION_CUSTOM_LABEL';
export const SET_OPERATION_CATEGORY = 'SET_OPERATION_CATEGORY';
export const SET_OPERATION_TYPE = 'SET_OPERATION_TYPE';
export const SET_SUBOPERATIONS = 'SET_SUBOPERATIONS';
export const UPDATE_ALERT = 'UPDATE_ALERT';

// UI
export const SET_ACCESS_ID = 'SET_ACCESS_ID';
export const SET_ACCOUNT_ID = 'SET_ACCOUNT_ID';
export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';
export const SET_SEARCH_FIELDS = 'SET_SEARCH_FIELDS';
export const RESET_SEARCH = 'RESET_SEARCH';

// Categories
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

// Settings
export const IMPORT_INSTANCE = 'IMPORT_INSTANCE';
export const NEW_STATE = 'NEW_STATE';
export const SET_SETTING = 'SET_SETTING';
export const UPDATE_ACCESS = 'UPDATE_ACCESS';
export const UPDATE_WEBOOB = 'UPDATE_WEBOOB';
