FROM node:18
LABEL maintainer="Benjamin Bouvier <public@benj.me>"

# Try to keep the number of RUN statements low to avoid creating too many
# layers, and try to ensure that each layer would be useful to cache.

# Install Woob OS-level dependencies.
RUN apt-get update \
 && apt-get install -y python3 python3-dev python3-pip python3-jose \
    locales git libffi-dev \
    libxml2-dev libxslt-dev libyaml-dev libtiff-dev libjpeg-dev libopenjp2-7-dev zlib1g-dev \
    libfreetype6-dev libwebp-dev build-essential gcc g++ wget unzip mupdf-tools \
 && rm -rf /var/lib/apt/lists/;

COPY ./config.example.ini /opt/config.ini
COPY ./entrypoint.sh /entrypoint.sh

# Mundane tasks, all in one to reduce the number of layers:
# - Make sure the UTF-8 locale exists and is used by default.
# - Make sure python3 is used as default python version and link pip to pip3.
# - Then setup Kresus layout.
# - Tweak executable rights.
RUN locale-gen C.UTF-8 && \
    update-locale C.UTF-8 && \
    update-alternatives --install /usr/bin/python python $(which python3) 1 && \
    useradd -d /home/user -m -s /bin/bash -U user && \
    mkdir -p /home/user/data && \
    chmod -x /opt/config.ini && \
    chmod +x /entrypoint.sh;

# Install Rust for some Python dependencies.
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
ENV PATH="/root/.cargo/bin:${PATH}"

# Install Python dependencies.
RUN pip install --break-system-packages --upgrade setuptools && \
    # Selenium 4.1.4+ requires python 3.8+ whereas woob 3.6 still supports 3.7, so every module using selenium in woob requires < 4.1.4
    pip install --break-system-packages "selenium<4.1.4" && \
    pip install --break-system-packages simplejson BeautifulSoup4 PyExecJS typing-extensions pdfminer.six Pillow pycountry Crypto jwt xlrd chompjs schwifty deprecated;

# Install and compile the app.
RUN cd /home/user && \
    wget https://github.com/kresusapp/kresus/archive/main.zip && \
    unzip main.zip && \
    rm main.zip && \
    mv kresus-main app && \
    cd /home/user/app && \
    yarn && \
    yarn build:prod && \
    rm -rf node_modules && \
    yarn add sqlite3 && \
    yarn --production;

WORKDIR /home/user/app

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV HOST=0.0.0.0
ENV KRESUS_DIR=/home/user/data
ENV NODE_ENV=production
ENV KRESUS_PYTHON_EXEC=python3
ENV IS_NIGHTLY=1

VOLUME /home/user/data

EXPOSE 9876

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/home/user/app/bin/kresus.js --config /opt/config.ini"]
