FROM node:10
MAINTAINER Benjamin Bouvier <public@benj.me>

# Install Weboob OS-level dependencies.
RUN apt-get update \
 && apt-get install -y locales git python3 python3-dev python3-pip libffi-dev \
    libxml2-dev libxslt-dev libyaml-dev libtiff-dev libjpeg-dev zlib1g-dev \
    libfreetype6-dev libwebp-dev build-essential gcc g++ wget unzip mupdf-tools \
 && rm -rf /var/lib/apt/lists/;

# Make sure python3 is used as default python version.
RUN update-alternatives --install /usr/bin/python python $(which python3) 1

# Entrypoint script expects "pip" instead of "pip3".
RUN ln -s $(which pip3) /usr/bin/pip

# Install Weboob python dependencies
RUN pip install --upgrade setuptools && \
    pip install simplejson BeautifulSoup4 PyExecJS pdfminer.six;

# Setup kresus layout.
RUN useradd -d /home/user -m -s /bin/bash -U user && \
    mkdir -p /home/user/data && \
    mkdir -p /weboob;

COPY ./config.example.ini /opt/config.ini
RUN chmod -x /opt/config.ini
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# -> Install and compile the app.
RUN cd /home/user && \
    wget https://github.com/kresusapp/kresus/archive/master.zip && \
    unzip master.zip && \
    rm master.zip && \
    mv kresus-master app && \
    cd /home/user/app && \
    npm install && \
    npm run build:prod && \
    rm -rf node_modules && \
    npm install --production && \
    chown -R user:user /home/user;

WORKDIR /home/user/app

# Make sure there is a UTF-8 locale set to avoid further python decoding issues.
RUN locale-gen C.UTF-8 && update-locale C.UTF-8

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV HOST 0.0.0.0
ENV KRESUS_DIR /home/user/data
ENV KRESUS_WEBOOB_DIR /weboob
ENV NODE_ENV production
ENV KRESUS_PYTHON_EXEC python3

VOLUME /home/user/data
VOLUME /weboob
EXPOSE 9876

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/home/user/app/bin/kresus.js --config /opt/config.ini"]
