FROM node:6
MAINTAINER Benjamin Bouvier <public@benj.me>

# Install Weboob OS-level dependencies.
RUN apt-get update && \
    apt-get install -y git python python-dev libffi-dev \
    libxml2-dev libxslt-dev libyaml-dev libtiff-dev libjpeg-dev zlib1g-dev \
    libfreetype6-dev libwebp-dev build-essential gcc g++ wget;

# Install Weboob python dependencies
RUN mkdir /tmp/install && cd /tmp/install && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python ./get-pip.py && \
    pip install -U setuptools && \
    pip install html2text simplejson BeautifulSoup PyExecJS && \
    rm -rf /tmp/install

# Setup kresus layout.
RUN useradd -d /home/user -m -s /bin/bash -U user && \
    mkdir -p /home/user/data && \
    mkdir -p /home/user/app && \
    chown -R user:user /home/user/app && \
    mkdir -p /weboob;

# -> Install app dependencies.
USER user
WORKDIR /home/user/app

COPY ./package.json /home/user/app
RUN npm install

COPY ./.babelrc /home/user/app/.babelrc
COPY ./bin /home/user/app/bin
COPY ./client /home/user/app/client
COPY ./scripts /home/user/app/scripts
COPY ./server /home/user/app/server
COPY ./shared /home/user/app/shared
COPY ./static /home/user/app/static
COPY ./webpack.config.js /home/user/app/

USER root

ENV HOST 0.0.0.0
ENV KRESUS_DIR /home/user/data
ENV KRESUS_WEBOOB_DIR /weboob

VOLUME /home/user/data
VOLUME /weboob
EXPOSE 9876

COPY ./docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/home/user/app/bin/kresus.js"]
