FROM bnjbvr/kresus-nightly-base
MAINTAINER Benjamin Bouvier <public@benj.me>

WORKDIR /home/user/app

RUN npm run build:prod

ENV NODE_ENV production

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/home/user/app/bin/kresus.js"]
