FROM janx/ubuntu-dev
MAINTAINER Benjamin Bouvier <public@benj.me>

# Global install of weboob.
USER root

# Weboob and its dependencies.
RUN apt-get update && \
    apt-get install -y python python-dev libffi-dev \
    libxml2-dev libxslt-dev libyaml-dev libtiff-dev libjpeg-dev zlib1g-dev \
    libfreetype6-dev libwebp-dev build-essential gcc g++ wget;

RUN cd /tmp && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python ./get-pip.py && \
    pip install -U setuptools && \
    pip install html2text simplejson BeautifulSoup PyExecJS

RUN git clone https://git.weboob.org/weboob/devel /tmp/weboob \
    && cd /tmp/weboob \
    && python ./setup.py install \
    && rm -rf /tmp/weboob

# Setup kresus layout.
USER user
RUN mkdir -p /home/user/kresus/data

# Install app and dependencies.
WORKDIR /home/user/kresus
RUN git clone https://framagit.org/bnjbvr/kresus app

WORKDIR /home/user/kresus/app
RUN npm install && make build

# Useful environment variables.
RUN echo "\n# Kresus configuration." >> /home/user/.bashrc \
 && echo "export KRESUS_DIR=\"/home/user/kresus/data\"" >> /home/user/.bashrc \
 && echo "export HOST=\"0.0.0.0\"" >> /home/user/.bashrc \
 && echo "export PORT=\"9876\"" >> /home/user/.bashrc \
 && echo "export KRESUS_URL_PREFIX=/`cat /proc/self/cgroup | grep docker | head -n 1 | sed 's_^.*docker\/__'`/\$PORT" >> /home/user/.bashrc

# Configure Cloud9 to use Kresus's source directory as workspace (-w).
RUN sudo sed -i "s/-w \/home\/user/-w \/home\/user\/kresus\/app/" /etc/supervisord.conf

# Expose the port on which Kresus will be running.
EXPOSE 9876

# Become root again so that supervisord is run with the right permissions.
USER root
