import * as path from 'path';
import { createConnection } from 'typeorm';

import { assert, makeLogger } from '../helpers';

import AccessFields from './access-fields';
import Accesses from './accesses';
import Accounts from './accounts';
import Alerts from './alerts';
import Budgets from './budgets';
import Categories from './categories';
import Settings from './settings';
import Transactions from './transactions';

import User from './users';

let log = makeLogger('models/index');

function makeOrmConfig() {
    let ormConfig = null;

    // Keep this switch in sync with ../config.js!
    switch (process.kresus.dbType) {
        case 'sqlite':
            assert(
                typeof process.kresus.sqlitePath !== 'undefined',
                'missing db path in server/models'
            );
            ormConfig = {
                type: 'sqlite',
                database: process.kresus.sqlitePath
            };
            break;

        case 'postgres':
        case 'mysql':
        case 'mariadb':
            assert(typeof process.kresus.dbHost === 'string', 'missing db host in server/models');
            assert(typeof process.kresus.dbPort === 'number', 'missing db port in server/models');
            assert(
                typeof process.kresus.dbUsername === 'string',
                'missing db username in server/models'
            );
            assert(
                typeof process.kresus.dbPassword === 'string',
                'missing db password in server/models'
            );
            assert(typeof process.kresus.dbName === 'string', 'missing db name in server/models');
            ormConfig = {
                type: process.kresus.dbType,
                host: process.kresus.dbHost,
                port: process.kresus.dbPort,
                username: process.kresus.dbUsername,
                password: process.kresus.dbPassword,
                database: process.kresus.dbName
            };
            break;
        default:
            assert(false, 'unexpected db type in server/models');
    }

    ormConfig.logging = process.kresus.dbLog;

    return ormConfig;
}

export async function setupOrm() {
    let ormConfig = Object.assign(makeOrmConfig(), {
        // Automatically run migrations.
        migrationsRun: true,

        // Entity models.
        entities: [path.join(__dirname, 'entities/*.js')],

        // Migration files.
        migrations: [path.join(__dirname, 'migrations/*.js')],

        // Automatically synchronize the database schema on startup. Very
        // unsafe, use only to look at queries generated by the ORM.
        synchronize: false
    });

    await createConnection(ormConfig);
}

export async function initModels(appOptions) {
    await setupOrm();

    let userId;
    if (process.kresus.providedUserId !== null) {
        userId = process.kresus.providedUserId;
        // Check that the user actually exists already.
        let user = await User.find(userId);
        if (!user) {
            throw new Error(
                `The user with provided ID ${userId} doesn't exist. Did you run "kresus create:user" first?`
            );
        }
    } else {
        // Create default user.
        let user = await User.find();
        if (!user) {
            let { login } = process.kresus.user;
            assert(login, 'There should be a default login set!');
            user = await User.create({ login });
            log.info('Creating default user...');
        }
        userId = user.id;
    }
    process.kresus.user.id = userId;
    log.info(`User has id ${userId}`);

    // Try to migrate the older Pouchdb database, if it's not been done yet.
    let didMigrate = await Settings.findOrCreateDefaultBooleanValue(userId, 'migrated-from-cozydb');
    log.info(`Checking if the migration from CozyDB is required... ${didMigrate ? 'no' : 'yes'}`);
    if (!didMigrate) {
        let all = require('../controllers/v1/all');
        let exportCozyDb = require('kresus-export-cozydb');
        let options = Object.assign({}, appOptions);
        log.info('Migrating from CozyDB...');
        try {
            let world = await exportCozyDb.run(options);
            await all.importData(userId, world);

            log.info('Migrating from CozyDB done!');
            await Settings.updateByKey(userId, 'migrated-from-cozydb', true);
        } catch (err) {
            log.error(`Unable to migrate from CozyDB: ${err.message}
${err.stack}`);

            log.info('Removing partially imported data...');

            // Remove all associated data, except for settings; they'll be
            // properly clobbered during the next successful attempt.
            await AccessFields.destroy(userId);
            await Accesses.destroy(userId);
            await Accounts.destroy(userId);
            await Alerts.destroy(userId);
            await Categories.destroy(userId);
            await Budgets.destroy(userId);
            await Transactions.destroy(userId);

            log.info('Removing partially imported data: done!');
        }
    }
}
