// Settings.
export const APPRISE_URL = 'apprise-url';
export const BUDGET_DISPLAY_NO_THRESHOLD = 'budget-display-no-threshold';
export const BUDGET_DISPLAY_PERCENT = 'budget-display-percent';
export const DARK_MODE = 'dark-mode';
export const DEFAULT_ACCOUNT_ID = 'default-account-id';
export const DEFAULT_CHART_DISPLAY_TYPE = 'default-chart-display-type';
export const DEFAULT_CHART_FREQUENCY = 'default-chart-frequency';
export const DEFAULT_CHART_PERIOD = 'default-chart-period';
export const DEFAULT_CHART_TYPE = 'default-chart-type';
export const DEFAULT_CURRENCY = 'default-currency';
export const DEMO_MODE = 'demo-mode';
export const DISCOVERY_MODE = 'discovery-mode';
export const DUPLICATE_IGNORE_DIFFERENT_CUSTOM_FIELDS = 'duplicate-ignore-different-custom-fields';
export const DUPLICATE_THRESHOLD = 'duplicate-threshold';
export const EMAIL_RECIPIENT = 'email-recipient';
export const FLUID_LAYOUT = 'fluid-layout';
export const LOCALE = 'locale';
export const LIMIT_ONGOING_TO_CURRENT_MONTH = 'limit-ongoing-to-current-month';
export const WOOB_AUTO_MERGE_ACCOUNTS = 'weboob-auto-merge-accounts'; // legit: avoid a migration
export const WOOB_AUTO_UPDATE = 'weboob-auto-update'; // legit: avoid a migration
export const WOOB_ENABLE_DEBUG = 'weboob-enable-debug'; // legit: avoid a migration
export const WOOB_FETCH_THRESHOLD = 'weboob-fetch-threshold'; // legit: avoid a migration
